name: Trigger Root Update

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Action in .ROOT
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPENDENCY_UPDATE_TOKEN }}" \
            https://api.github.com/repos/MeinChatserver/.ROOT/dispatches \
            -d '{"event_type":"submodule_updated"}'
